/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import java.awt.CardLayout;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.SwingUtilities;

/**
 *
 * @author Hp Pc
 */
public final class frm_menu_precios extends javax.swing.JFrame {

    /**
     * Creates new form frm_menu_usuario
     */
    pnl_alta_precio pnl_alta_precio = new pnl_alta_precio();
    pnl_modificacion_precio pnl_modificacion_precio = new pnl_modificacion_precio();
    pnl_busqueda_precio pnl_busqueda_precio = new pnl_busqueda_precio();
    pnl_listado_precio pnl_lisatdo_precio = new pnl_listado_precio();
    CardLayout vista;
    

    public frm_menu_precios() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        iconoFormulario();
        vista = (CardLayout) pnl_vista_principal.getLayout();
    }

    public void iconoFormulario() {
        URL url = getClass().getResource("/imagenes/iconoDelSistema.png");
        ImageIcon iconFormulario = new ImageIcon(url);
        setIconImage(iconFormulario.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_modificacionPR = new javax.swing.JToggleButton();
        btn_consultaPR = new javax.swing.JToggleButton();
        btn_altaPR = new javax.swing.JToggleButton();
        btn_listadoPR = new javax.swing.JToggleButton();
        btn_salirU = new javax.swing.JButton();
        pnl_vista_principal = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestión de usuarios");

        jPanel1.setBackground(new java.awt.Color(204, 0, 153));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Menu del sistema");

        btn_modificacionPR.setBackground(new java.awt.Color(204, 204, 204));
        btn_modificacionPR.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btn_modificacionPR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/modificacionPrecio.png"))); // NOI18N
        btn_modificacionPR.setText("Modificar precio de un producto");
        btn_modificacionPR.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_modificacionPR.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btn_modificacionPR.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btn_modificacionPR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modificacionPRActionPerformed(evt);
            }
        });

        btn_consultaPR.setBackground(new java.awt.Color(204, 204, 204));
        btn_consultaPR.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btn_consultaPR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/busqueda.png"))); // NOI18N
        btn_consultaPR.setSelected(true);
        btn_consultaPR.setText("Buscar un recio");
        btn_consultaPR.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_consultaPR.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btn_consultaPR.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btn_consultaPR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_consultaPRActionPerformed(evt);
            }
        });

        btn_altaPR.setBackground(new java.awt.Color(204, 204, 204));
        btn_altaPR.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btn_altaPR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/altaPrecio.png"))); // NOI18N
        btn_altaPR.setText("Registro de un nuevo precio");
        btn_altaPR.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_altaPR.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btn_altaPR.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btn_altaPR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_altaPRActionPerformed(evt);
            }
        });

        btn_listadoPR.setBackground(new java.awt.Color(204, 204, 204));
        btn_listadoPR.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btn_listadoPR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/listado.png"))); // NOI18N
        btn_listadoPR.setText("Ver listado de precios");
        btn_listadoPR.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_listadoPR.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btn_listadoPR.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btn_listadoPR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_listadoPRActionPerformed(evt);
            }
        });

        btn_salirU.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_salirU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salir.png"))); // NOI18N
        btn_salirU.setText("Salir");
        btn_salirU.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_salirU.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btn_salirU.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btn_salirU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirUActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_listadoPR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_modificacionPR, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                            .addComponent(btn_consultaPR, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_altaPR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addComponent(btn_salirU))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(btn_altaPR, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_modificacionPR, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_consultaPR, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_listadoPR, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(btn_salirU)
                .addContainerGap())
        );

        pnl_vista_principal.setBackground(new java.awt.Color(204, 0, 153));
        pnl_vista_principal.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl_vista_principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnl_vista_principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 696, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_modificacionPRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modificacionPRActionPerformed
        pnl_vista_principal.add(pnl_modificacion_precio,"Modificacion");
        vista.show(pnl_vista_principal, "Modificacaion");
        SwingUtilities.updateComponentTreeUI(this);
        this.repaint();
    }//GEN-LAST:event_btn_modificacionPRActionPerformed

    private void btn_consultaPRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_consultaPRActionPerformed
        pnl_vista_principal.add(pnl_busqueda_precio,"Busqueda");
        vista.show(pnl_vista_principal, "Busqueda");
        SwingUtilities.updateComponentTreeUI(this);
        this.repaint();
    }//GEN-LAST:event_btn_consultaPRActionPerformed

    private void btn_altaPRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_altaPRActionPerformed
        pnl_vista_principal.add(pnl_alta_precio, "alta");
        vista.show(pnl_vista_principal, "alta");
        SwingUtilities.updateComponentTreeUI(this);
        this.repaint();
    }//GEN-LAST:event_btn_altaPRActionPerformed

    private void btn_listadoPRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_listadoPRActionPerformed
        pnl_vista_principal.add(pnl_lisatdo_precio,"Listado");
        vista.show(pnl_vista_principal, "Listado");
        SwingUtilities.updateComponentTreeUI(this);
        this.repaint();
    }//GEN-LAST:event_btn_listadoPRActionPerformed

    private void btn_salirUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirUActionPerformed
        System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_salirUActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_menu_precios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_menu_precios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_menu_precios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_menu_precios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_menu_precios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btn_altaPR;
    private javax.swing.JToggleButton btn_consultaPR;
    private javax.swing.JToggleButton btn_listadoPR;
    private javax.swing.JToggleButton btn_modificacionPR;
    private javax.swing.JButton btn_salirU;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel pnl_vista_principal;
    // End of variables declaration//GEN-END:variables
}
